[phases.setup]
nixPkgs = ["jdk11", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dserver.address=0.0.0.0 -jar target/question-bank-1.0.0.jar"

